# Fast Development Pre-commit Configuration
# Optimized for rapid iteration - only essential checks
# For full quality checks, run: make quality-check
# To restore full pre-commit: cp .pre-commit-config.yaml.full .pre-commit-config.yaml

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-merge-conflict
      - id: check-added-large-files
        args: ['--maxkb=10000']  # 10MB limit

  - repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
      - id: black
        language_version: python3.11

# Removed for fast iteration:
# - isort (can be slow)
# - flake8 (can find many issues)
# - mypy (type checking is slow)
# - prettier (formatting can be slow)
# - eslint (linting can be slow)
#
# These are still available via:
# - make lint (runs all linters)
# - make format (runs all formatters)
# - make quality-check (runs everything)
